# Dockerfile
FROM python:3.12-slim

WORKDIR /app

# Copy the dependency file and install packages
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the code
COPY . .

# Run the API on container start
CMD ["uvicorn", "main-async:app", "--host", "0.0.0.0", "--port", "8001"]
